apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: k6
    user: admin
    secureJsonData:
      token: my-super-secret-admin-token
    jsonData:
      version: Flux
      organization: aig
      defaultBucket: k6
      tlsSkipVerify: true
    isDefault: true
    editable: false

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
    editable: false