#!/usr/bin/env python3
"""
AIGestion Jules Free-Tier Dispatch (GT-01)
==========================================
Configuration and dispatcher for Google Jules autonomous coding agent.
Uses the free tier: 15 tasks/day, 3 concurrent, Gemini 3 Flash.

When a user approves a proposal card in the chat UI, DanielaOS sends the
task to Jules, which clones the repo, implements the change, runs tests,
and opens a GitHub PR.

Free tier: 15 tasks/day, 3 concurrent, $0/month.

CLI: python jules_free_dispatch.py status|dispatch "task"|queue|pr-config
"""

import json
import sys
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent
STATE_FILE = PROJECT_ROOT / "data" / "jules_dispatch_state.json"


# ==============================================================================
# JULES FREE-TIER CONFIG
# ==============================================================================

JULES_CONFIG = {
    "free_tier": {
        "tasks_per_day": 15,
        "concurrent_tasks": 3,
        "model": "gemini-3.6-flash",
        "cost": "0 EUR/month",
        "features": [
            "Async task execution in Google Cloud VMs",
            "Clones repo, multi-file changes, opens GitHub PRs",
            "Automatic test running",
            "SOC 2 Type II, ISO 27001 certified",
        ],
    },
    "repository": {
        "github_repo": "aigestion",  # Update with actual repo
        "default_branch": "main",
        "pr_template": "## Changes\n\n{description}\n\n## Task\n\n{task_prompt}\n\n## Model\n\nGenerated by Jules (free tier) via DanielaOS",
    },
    "integrations": [
        {"name": "GitHub", "status": "connected", "notes": "PR creation and review"},
        {
            "name": "Android Studio CLI",
            "status": "available",
            "notes": "Build, test, emulator for android_app/",
        },
        {
            "name": "Firebase AI Logic",
            "status": "available",
            "notes": "Agent-native backend (future GT-03)",
        },
        {
            "name": "MCP Partners",
            "status": "available",
            "notes": "Linear, Supabase, Neon, Tinybird, Context7",
        },
    ],
}


# ==============================================================================
# TASK QUEUE
# ==============================================================================


@dataclass
class JulesTask:
    """A task dispatched to Jules for autonomous coding."""

    id: str
    title: str
    description: str
    files_hint: list[str] = field(default_factory=list)
    test_required: bool = True
    priority: str = "normal"  # urgent, high, normal, low
    status: str = "queued"  # queued, dispatched, in_progress, pr_opened, merged, failed
    created_at: str = ""
    dispatched_at: str = ""
    pr_url: str = ""
    pr_number: int = 0
    jules_task_id: str = ""


class JulesDispatcher:
    """Manages the Jules free-tier task queue (15 tasks/day)."""

    DAILY_LIMIT = 15

    def __init__(self):
        self.state = self._load_state()

    def _load_state(self) -> dict:
        if STATE_FILE.exists():
            return json.loads(STATE_FILE.read_text(encoding="utf-8"))
        return {"tasks": [], "daily_count": {}, "last_reset": datetime.now().isoformat()}

    def _save_state(self):
        STATE_FILE.parent.mkdir(parents=True, exist_ok=True)
        STATE_FILE.write_text(
            json.dumps(self.state, indent=2, ensure_ascii=False), encoding="utf-8"
        )

    def _today_key(self) -> str:
        return datetime.now().strftime("%Y-%m-%d")

    def _get_daily_count(self) -> int:
        today = self._today_key()
        return self.state["daily_count"].get(today, 0)

    def can_dispatch(self) -> bool:

        return self._get_daily_count() < self.DAILY_LIMIT

    def get_remaining_today(self) -> int:

        return self.DAILY_LIMIT - self._get_daily_count()

    def queue_task(
        self, title: str, description: str, files_hint: list[str] = None, priority: str = "normal"
    ) -> JulesTask:
        """Queue a task for Jules dispatch."""
        task = JulesTask(
            id=f"JULES-{len(self.state['tasks']) + 1:04d}",
            title=title,
            description=description,
            files_hint=files_hint or [],
            priority=priority,
            created_at=datetime.now().isoformat(),
        )
        self.state["tasks"].append(asdict(task))
        self._save_state()
        return task

    def dispatch_task(self, task_id: str) -> dict:
        """
        Dispatch a queued task to Jules.

        In production, this would call the Jules API:
        POST https://jules.google/api/v1/tasks
        {
            "repository": "github.com/user/aigestion",
            "prompt": task.description,
            "files": task.files_hint,
            "model": "gemini-2.5-flash"
        }

        For now, this prepares the dispatch payload and marks the task.
        """
        task = None
        for t in self.state["tasks"]:
            if t["id"] == task_id:
                task = t
                break

        if not task:
            return {"error": f"Task {task_id} not found"}

        if not self.can_dispatch():
            return {"error": f"Daily limit reached ({self.DAILY_LIMIT} tasks/day). Try tomorrow."}

        # Prepare Jules API payload (ready for integration)
        jules_payload = {
            "repository": JULES_CONFIG["repository"]["github_repo"],
            "branch": JULES_CONFIG["repository"]["default_branch"],
            "prompt": f"{task['title']}\n\n{task['description']}",
            "files_hint": task["files_hint"],
            "run_tests": task["test_required"],
            "model": JULES_CONFIG["free_tier"]["model"],
            "pr_template": JULES_CONFIG["repository"]["pr_template"],
        }

        # Mark as dispatched
        task["status"] = "dispatched"
        task["dispatched_at"] = datetime.now().isoformat()
        task["jules_payload"] = jules_payload

        # Increment daily count
        today = self._today_key()
        self.state["daily_count"][today] = self.state["daily_count"].get(today, 0) + 1

        self._save_state()

        return {
            "task_id": task_id,
            "status": "dispatched",
            "jules_payload": jules_payload,
            "remaining_today": self.get_remaining_today(),
            "note": "Payload ready. Connect Jules API to enable real dispatch.",
        }

    def mark_pr_opened(self, task_id: str, pr_url: str, pr_number: int):
        """Mark a task as having an open PR from Jules."""
        for t in self.state["tasks"]:
            if t["id"] == task_id:
                t["status"] = "pr_opened"
                t["pr_url"] = pr_url
                t["pr_number"] = pr_number
                self._save_state()
                return True
        return False

    def get_queue(self) -> list[dict]:
        """Get all tasks in the queue."""
        return self.state["tasks"]

    def get_status(self) -> dict:

        self._today_key()
        tasks = self.state["tasks"]
        by_status = {}
        for t in tasks:
            by_status.setdefault(t["status"], 0)
            by_status[t["status"]] += 1

        return {
            "free_tier": JULES_CONFIG["free_tier"],
            "daily_limit": self.DAILY_LIMIT,
            "used_today": self._get_daily_count(),
            "remaining_today": self.get_remaining_today(),
            "total_tasks": len(tasks),
            "by_status": by_status,
            "integrations": JULES_CONFIG["integrations"],
        }


# ==============================================================================
# GITHUB PR WEBHOOK CONFIG (for receiving Jules PR notifications)
# ==============================================================================

GITHUB_WEBHOOK_CONFIG = {
    "endpoint": "/api/webhooks/github",
    "events": ["pull_request"],
    "actions": ["opened", "updated", "closed", "merged"],
    "secret_env": "GITHUB_WEBHOOK_SECRET",
    "on_pr_opened": [
        "Notify Daniela in chat: 'Jules opened PR #{number}: {title}'",
        "Run Chrome DevTools for Agents to verify frontend changes",
        "Trigger ANALYST agent to review the PR",
        "Show proposal card update in dashboard",
    ],
    "on_pr_merged": [
        "Mark task as completed in JulesDispatcher state",
        "Notify Daniela: 'PR merged successfully'",
        "Trigger CODER agent to run post-merge tests",
        "Update metrics: tasks_completed++",
    ],
}


# ==============================================================================
# CLI
# ==============================================================================


def print_status():
    dispatcher = JulesDispatcher()
    status = dispatcher.get_status()

    print("\n" + "=" * 60)

    print("  JULES FREE-TIER DISPATCH (GT-01)")
    print("=" * 60)

    print("\n  FREE TIER:")
    print(f"    Tasks/day: {status['free_tier']['tasks_per_day']}")
    print(f"    Concurrent: {status['free_tier']['concurrent_tasks']}")
    print(f"    Model: {status['free_tier']['model']}")
    print(f"    Cost: {status['free_tier']['cost']}")

    print("\n  TODAY:")
    print(f"    Used: {status['used_today']}/{status['daily_limit']}")
    print(f"    Remaining: {status['remaining_today']}")

    print("\n  QUEUE:")
    print(f"    Total tasks: {status['total_tasks']}")
    for status_name, count in status["by_status"].items():
        print(f"    {status_name}: {count}")

    print("\n  INTEGRATIONS:")
    for integ in status["integrations"]:
        print(f"    {integ['name']}: {integ['status']} — {integ['notes']}")

    print("\n  GITHUB WEBHOOK:")
    print(f"    Endpoint: {GITHUB_WEBHOOK_CONFIG['endpoint']}")
    print(f"    Events: {', '.join(GITHUB_WEBHOOK_CONFIG['events'])}")

    print("\n" + "=" * 60)


def main():
    if len(sys.argv) > 1:
        cmd = sys.argv[1]
        dispatcher = JulesDispatcher()

        if cmd == "status":
            print_status()

        elif cmd == "dispatch":
            if len(sys.argv) < 3:
                print('Usage: python jules_free_dispatch.py dispatch "task description"')
                return
            description = sys.argv[2]
            task = dispatcher.queue_task(
                title=description[:60],
                description=description,
                priority="normal",
            )
            result = dispatcher.dispatch_task(task.id)
            print(f"\nQueued task: {task.id}")
            print(f"Title: {task.title}")
            print(json.dumps(result, indent=2, ensure_ascii=False))

        elif cmd == "queue":
            tasks = dispatcher.get_queue()
            print(f"\nTask Queue ({len(tasks)} tasks):")
            for t in tasks:
                print(f"  [{t['id']}] {t['title']} — {t['status']}")

        elif cmd == "pr-config":
            print("\nGitHub PR Webhook Configuration:")
            print(json.dumps(GITHUB_WEBHOOK_CONFIG, indent=2, ensure_ascii=False))

        else:
            print(f"Unknown command: {cmd}")
            print("Usage: python jules_free_dispatch.py [status|dispatch|queue|pr-config]")
    else:
        print_status()


if __name__ == "__main__":
    main()
