apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - daniela.yaml
  - hermes.yaml
  - engines/intel.yaml
  - engines/auto.yaml
  - engines/data.yaml
  - engines/secure.yaml
  - engines/devtools.yaml
  - engines/ecosystem.yaml
  - engines/ux.yaml
  - engines/scale.yaml
  - engines/chaos.yaml
  - engines/brand.yaml

commonLabels:
  app.kubernetes.io/part-of: aig
  app.kubernetes.io/managed-by: kustomize

images:
  - name: daniela
    newTag: "1.0.0"
  - name: hermes
    newTag: "1.0.0"